package model

object Constants {
	const val MIN_RANDOM_VALUE = 0
	const val MAX_RANDOM_VALUE = 500

	const val DEFAULT_VERTEX_RADIUS = 25
	const val DEFAULT_BORDER_WIDTH = 5
	const val DEFAULT_EDGE_WIDTH = 2

	const val DEFAULT_ARROW_TRIANGLE_HEIGHT = 30
	const val DEFAULT_ARROW_TRIANGLE_WIDTH = 10
	const val DEFAULT_LOOP_RADIUS_COEFF = 0.75f
	const val DEFAULT_LOOP_MULTIPLIER = 3

	const val DEFAULT_ZOOM_SCALE_COEF = .001f

	const val SHOW_LABEL_MOD = 3

	const val BANNER_HEIGHT = 50

	//Colors
	const val PALE_YELLOW = 0xFFFAF3C0
	const val DEFAULT_PATH_COLOR = 0xFFFF0000
	const val SEMI_BLACK = 0x50000000
	const val BRIGHT_RED = 0xFFFF0000
	const val DEFAULT_EDGE_COLOR = 0xFF000000
	const val DEFAULT_VERTEX_COLOR = 0xFF2979FF
	const val DEFAULT_VERTEX_BORDER_COLOR = 0xFF2962FF
}
